### ISSUE TITLE
docs for getting all prompts have incorrect return type

### ISSUE THREAD

**Issue by abubakarsohail** [MagnivOrg/prompt-layer-docs#9]
The API is supposed to return `id` and not `api_key`

![Image](https://github.com/MagnivOrg/prompt-layer-docs/assets/20099503/85ccf9aa-e007-40db-9b9e-8e44b39538a7)

**Comment by Jped** [comment]
@abubakarsohail I am going to fix this -- but a small issue like this should be quickly fixed instead of opening up an issue
